<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXI6DBVR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXI6DBVR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXI6DBVR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXI6DBVR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXI6DBVR\App_KernelDevDebugContainer([
    'container.build_hash' => 'XI6DBVR',
    'container.build_id' => 'a1e0eb7c',
    'container.build_time' => 1642171906,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXI6DBVR');
